### ISSUE TITLE
FiberError: cannot resume transferred Fiber 

### ISSUE THREAD

**Issue by wulftone** [paddor/em-simple_telnet#2]
I tried your example and it failed with the following error:

```
/home/wulftone/.rvm/gems/ruby-2.0.0-p247/gems/em-simple_telnet-0.0.13/lib/em-simple_telnet.rb:362:in `resume': cannot resume transferred Fiber (FiberError)
	from /home/wulftone/.rvm/gems/ruby-2.0.0-p247/gems/em-simple_telnet-0.0.13/lib/em-simple_telnet.rb:362:in `block in initialize'
	from /home/wulftone/.rvm/gems/ruby-2.0.0-p247/gems/em-simple_telnet-0.0.13/lib/em-simple_telnet.rb:957:in `call'
	from /home/wulftone/.rvm/gems/ruby-2.0.0-p247/gems/em-simple_telnet-0.0.13/lib/em-simple_telnet.rb:957:in `connection_completed'
	from /home/wulftone/.rvm/gems/ruby-2.0.0-p247/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
	from /home/wulftone/.rvm/gems/ruby-2.0.0-p247/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
	from /home/wulftone/work/gmclient/lib/gmclient.rb:11:in `<top (required)>'
```

I'm not sure what this means!  Do you know?

**Comment by paddor** [comment]
Do you still have this issue?

**Comment by wulftone** [comment]
Yeah, I'm not working on this anymore, so I dunno!  Will close for now.  Maybe I'll get back to it some day.
